---
title: "Welcome to My Page"
date: 2021-07-01
---
title: Welcome to my page
author: Amehi
email: 1523049755@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Just for test, but it's so fun.

# social links
twitter_username: Amehi # DO NOT include the @ character, or else the build will fail!
github_username:  Amehi # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
theme: minima
